#!/usr/bin/env bash

# Load Global Variable
source $HOME/.idesktop

if [[ "$1" == "change" ]]; then
    urxvt -e ~/.config/i3/scripts/change-wallpaper
else
    if [[ $WALLPAPER == "DEFAULT" ]]; then
        if [[ $THEME == "iLight" ]]; then
            feh --bg-fill ~/.wallpaper/iLight-0.png
        elif [[ $THEME == "iDark" ]]; then
            feh --bg-fill ~/.wallpaper/iDark-0.png
        fi
    else
        feh --bg-fill $WALLPAPER
    fi
fi
